import Link from "next/Link"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <body>
        <div>
        <ul>
          <li><Link href="/">Home</Link></li>
          <li><Link href="/about">about</Link></li>
          <li><Link href="/erp">erp</Link></li>
        </ul>
        </div>
        <div>
        {children}
        </div>
      </body>
    </html>
  )
}
